spring.application.name=Expense-Tracker


spring.datasource.url=jdbc:postgresql://localhost:5432/Expenses
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true